var cl_name,
	cl_model,
	cl_sensitivity,
	cl_showTimeDelta,
	cl_timeNudge;

function RegisterCvars() {
	cl_name          = Cvar.AddCvar('name',             DefaultName(),  QS.CVAR.ARCHIVE | QS.CVAR.USERINFO);
	cl_model         = Cvar.AddCvar('model',           'sarge',         QS.CVAR.ARCHIVE | QS.CVAR.USERINFO);
	cl_sensitivity   = Cvar.AddCvar('cl_sensitivity',   2,              QS.CVAR.ARCHIVE);
	cl_showTimeDelta = Cvar.AddCvar('cl_showTimeDelta', 0,              QS.CVAR.ARCHIVE);
	cl_timeNudge     = Cvar.AddCvar('cl_timeNudge',     0,              QS.CVAR.ARCHIVE);
}

function DefaultName () {
	var prefixes,
		suffixes;

	prefixes = [
		'Unnamed',
		'Nut',
		'Fuck',
		'Fail',
		'Magic',
		'SonicThe',
		'Lame',
		'Porn',
		'Bearded',
		'Cold',
		'Tattooed',
		'Pigtailed',
		'Thick',
		'Musty',
		'Ugly',
		'Disgusting',
		'Fake',
		'Shirtless',
		'Murder',
		'Cool',
		'Awesome',
		'Drunken',
		'Space',
		'Young',
		'Black',
		'Terror',
		'Celebrity',
		'Dead',
		'Weird',
		'Hug',
		'White',
		'Floating',
		'Blood',
		'SelfTaught',
		'Wrong',
		'Locked',
		'Average',
		'Disappearing',
		'Laugh',
		'Moist',
		'Pink',
		'Super',
		'Half',
		'Bound',
		'Street',
		'Cave',
		'Metal',
		'Solid',
		'Shadow',
		'Doom',
		'Lost',
		'Heavenly',
		'Secret',
		'Monster',
		'Total',
		'Game',
		'Meat',
		'NobyNoby',
		'Dust',
		'Enemy',
		'Walking',
		'Mega'
	];

	suffixes = [
		'Player',
		'Case',
		'Face',
		'Whale',
		'Mike',
		'Hedgehog',
		'Guest',
		'Star',
		'Lady',
		'Clown',
		'Junk',
		'Kitchen',
		'City',
		'Symptom',
		'Sickness',
		'Bitches',
		'Truck',
		'Bag',
		'Lion',
		'Gopher',
		'Beans',
		'Sauce',
		'Robot',
		'Frog',
		'Fractions',
		'Chemistry',
		'Lung',
		'SmokeStacks',
		'Attack',
		'Jar',
		'Nihilist',
		'Anarchist',
		'Door',
		'Lightning',
		'Citizen',
		'Hooligan',
		'Whiskey',
		'Club',
		'Cocktail',
		'Friend',
		'Bassline',
		'Rhymes',
		'Kite',
		'Soldier',
		'King',
		'Beast',
		'Script',
		'Peer',
		'Light',
		'World',
		'Mario',
		'Life',
		'Mother',
		'Earth',
		'Man',
		'Champion',
		'Gear',
		'War',
		'Fighter',
		'Story',
		'Trigger',
		'Snake',
		'Eater',
		'Colossus',
		'Prime',
		'Viking',
		'Quest',
		'Hand',
		'Bride',
		'Hunter',
		'Spartan',
		'Warrior',
		'Boy',
		'Wrath',
		'Ninja',
		'Man'
	];

	return prefixes[Math.floor(Math.random() * prefixes.length)] + suffixes[Math.floor(Math.random() * suffixes.length)];
}
